# 4. 데이터 핸들링 - 판다스
판다스
- 대표적인 데이터 핸들링 프레임워크
- 2차원(행, 열) 데이터를 효율적으로 가공/처리
- 파이썬의 리스트, 컬렉션, 넘파이 등의 내부 데이터 뿐만 아니라 CSV 등의 파일을 쉽게 Dataframe으로 변경하여 데이터의 가공/분석을 편리하게 수행
- 핵심 객체: Dataframe(여러 개의 행과 열로 이뤄진 2차원의 데이터를 담는 데이터 구조체)

- index: RDBMS의 PK처럼 개별 데이터를 고유하게 식별하는 Key 값
- Series&Dataframe은 Index를 key 값으로 가지는데, Series는 칼럼이 하나, Dataframe은 칼럼이 여러 개인 데이터 구조체(=>여러 개의 Series로 이뤄짐)


## 1) 판다스 시작 - 파일을 Dataframe으로 로딩, 기본 ApI

In [1]:
import pandas as pd

- 판다스는 다양한 포맷으로 된 파일을 Dataframe으로 로딩할 수 있는 편리한 API 제공
- read_table()과 read_csv()의 차이: 필드 구분 문자(Delimeter)가 콤마(',') or 탭('\n')
- read_csv(): sep에 해당 구분 문자 입력(탭으로 필드가 구분이 되어 있다면 read_csv('파일명', sep='\t')처럼 씀) / sep 인자 생략 시, 자동으로 콤마(,)로 할당 (sep=',')
- read_fwf(): Fixed Width, 고정 길이 기반의 칼럼 포맷을 Dataframe으로 로딩하기 위한 API

In [105]:
titanic_df = pd.read_csv('titanic_train.csv')
print('titanic 변수 type：', type(titanic_df))
titanic_df

titanic 변수 type： <class 'pandas.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 12 columns]

- pd.read_csv( )는 호출 시 파일명 인자로 들어온 파일을 로딩해 DataFrame 객체로 반환
- read_csv()는 별다른 파라미터 지정이 없으면 파일의 맨 처음 로우를 칼럼명으
로 인지하고 칼럼으로 변환
- 모든 DataFrame 내의 데이터는 생성되는 순간 고유의 Index 값을 가지며, Index는 고유의 레코드를 식별하는 역할을 함

In [106]:
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [107]:
print('DataFrame 크기: ', titanic_df.shape)

DataFrame 크기:  (891, 12)

- DataFrame은 데이터뿐만 아니라 칼럼의 타입, Null 데이터 개수, 데이터 분포도 등의 메타 데이터 등
도 조회가 가능 -> info(), describe()

In [108]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

- info( ) 메서드를 통해서 총 데이터 건수와 데이터 타입, Null 건수 파악
- describe() 메서드는 칼럼별 숫자형 데이터값의 n-percentile 분포도, 평균값, 최댓값, 최솟값을 나타내며, 오직 숫자형(int, float 등) 칼럼의 분포도만 조사하며 자동으로 object 타입의 칼럼은 출력에서 제외시킴

In [84]:
titanic_df.describe()

       PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

- count는 Not Null인 데이터 건수, mean은 전체 데이터의 평균값, std는 표준편차, min은 최솟값, max는 최댓값
- describe() 해당 숫자 칼럼이 숫자형 카테고리 칼럼인지를 판단할 수 있게 도와줌(카테고리 칼럼은 특정 범주에 속하는 값을 코드화한 칼럼)

In [85]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

- DataFrame의 [ ] 연산자 내부에 칼럼명을 입력하면 Series 형태로 특정 칼럼 데이터 세트가 반환
- 반환된 Series 객체에 value_counts() 메서드를 호출하면 해당 칼럼값의 유형과 건수 확인 (value_counts()는 데이터의 분포도를 확인
하는 데 매우 유용한 함수)

DataFrame의 [ ] 연산자 내부에 칼럼명을 입력하면
해당 칼럼에 해당하는 Series 객체를 반환
- Series는 Index와 단 하나의 칼럼으로 구성된 데이터 세트

In [86]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.Series'>

In [109]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [88]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

- value_counts( )가 반환하는 데이터 타입 역시 Series 객체이며, value_counts( )는 칼럼 값별 데이터 건수를 반환하므로 고유 칼럼 값을 식별자로 사용함
- 인덱스는 DataFrame, Series가 만들어진 후에도 변경할 수 있으며, 숫
자형뿐만 아니라 문자열도 가능(단, 모든 인덱스는 고유성이 보장돼야 함)

유의) value_counts() 메서드를 사용할 때는 Null 값을 무시하고 결괏값을 내놓기 쉬움
- value_counts()는 Null 값을 포함하여 개별 데이터 값의 건수를 계산할지를 dropna 인자로 판
단, dropna의 기본값은 True이며 Null 값을 무시하고 개별 데이터 값의 건수를 계산함

In [110]:
print('titanic_df 데이터 건수:',titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일.
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

## - 2) Dataframe과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

(1) 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

DataFrame으로 변환 시 칼럼명을 지정(지정하지 않으면 자동으로 칼럼명을 할당) - DataFrame은 리
스트와 넘파이 ndarray와 다르게 칼럼명을 가지고 있기 때문

In [111]:
import numpy as np
col_name1=['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape：', array1.shape )

# 리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame：\n', df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame：\n', df_array1)

array1 shape： (3,)
1차원 리스트로 만든 DataFrame：
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame：
    col1
0     1
1     2
2     3

주의) 1차원 형태의 데이터를 기반으로 DataFrame을 생성하므로 칼럼명이 한 개만 필요

In [112]:
# 3개의 칼럼명이 필요함.
col_name2=['col1','col2','col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape：', array2.shape )
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame：\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame：\n', df_array2)

array2 shape： (2, 3)
2차원 리스트로 만든 DataFrame：
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame：
    col1  col2  col3
0     1     2     3
1    11    12    13

딕셔너리를 DataFrame으로 변환 시에는 딕셔너리의 키(Key)는 칼럼명으로, 딕셔너리의 값(Value)은 키에 해당하는 칼럼 데이터
로 변환 -> 키의 경우는 문자열, 값의 경우 리스트(또는 ndarray) 형태로 딕셔너리를 구성

In [113]:
# Key는 문자열 칼럼명으로 매핑, Value는 리스트 형（또는 ndarray） 칼럼 데이터로 매핑
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame：\n', df_dict)

딕셔너리로 만든 DataFrame：
    col1  col2  col3
0     1     2     3
1    11    22    33

(2) DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

- 데이터 핸들링은 DataFrame을 이용하더라도 머신러닝 패키지의 입력 인자 등에 적용하기 위해 다시 넘파이
ndarray로 변환하는 경우가 빈번하게 발생
- DataFrame을 넘파이 ndarray로 변환: DataFrame 객체의 values를 이용

In [114]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shap:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shap: (2, 3)
[[ 1  2  3]
 [11 22 33]]

- 리스트로의 변환: values로 얻은 ndarray에 tolist()를 호출
- 딕셔너리로의 변환: DataFrame 객체의 to_dict() 메서드를 호출하는데, 인자로 list를 입력하면 딕셔너리의 값이 리스트형으로 반환

In [115]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolistO 타입:', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolistO 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

## - 3) DataFrame의 칼럼 데이터 세트 생성과 수정

DataFrame의 칼럼 데이터 세트 생성과 수정: [ ] 연산자를 이용

In [116]:
titanic_df['Age_0']=0
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [117]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1

- DataFrame 내의 기존 칼럼 값도 쉽게 일괄적으로 업데이트: 업데이트를 원하는 칼럼Series를 DataFrame [] 내에 칼럼명으로 입력한 뒤에 값을 할당

In [118]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

## - 4) DataFrame 데이터 삭제

- drop() 메서드를 이용
- drop() 메서드의 원형: DataFrame.drop(labels=None, axis=®, index=None, columns=None, leve!=None, inplace=False, errors='raise') -> 중요한 파라미터는 labels, axis, inplace
- axis=l을 입력하면 칼럼 축 방향으로 드롭을 수행하므로 칼럼을 드롭, labels에 원하는 칼럼명을 입력하고 axis=l을 입력하면 지정된 칼럼을 드롭함
- DataFrame의 특정 로우를 가리키는 것은 인덱스 -> axis를 0으로 지정하면 DataFrame은 자동으로 labels에 오는 값을 인덱스로 간주

In [119]:
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      360.0          1

In [120]:
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

- Inplace=False이면 자기 자신의 DataFrame의 데이터는 삭제하지 않으며, 삭제된 결과 DataFrame을 반환
- inplace=True로 설정하면 자신의 DataFrame의 데이터를 삭제
- 여러 개의 칼럼을 삭제: 리스트 형태로 삭제하고자 하는 칼럼명을 입력해 labels 파라미터로 입력

In [121]:
drop_result=titanic_df.drop(['Age_0','Age_by_10','Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값:', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값: None

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

- 유의) drop() 시 inplace=True로 설정하면 반환 값이 None(아무 값도 아님)이 됨 -> inplace=True로 설정한 채로 반환 값을 다시 자신의 DataFrame 객체로 할당하면 안됨

In [122]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0, 1, 2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

- axis： DataFrame의 로우를 삭제할 때는 axis=0, 칼럼을 삭제할 때는 axis=l으로 설정.
- 원본 DataFrame은 유지하고 드롭된 DataFrame을 새롭게 객체 변수로 받고 싶다면 inplace三False로 설정(디폴트 값이
False임).
예: titanic_drop_df = titanic_df.drop(' Age_0', axis三1, inplace三F게se )
- 원본 DataFrame에 드롭된 결과를 적용할 경우에는 inplace=True를 적용.
예: titanic_df.drop(1 Age_0’, axis=l, inplace=True )
- 원본 DataFrame에서 드롭된 DataFrame을 다시 원본 DataFrame 객체 변수로 할당하면 원본 DataFrame에서 드롭된
결과를 적용할 경우와 같음(단, 기존 원본 DataFrame 객체 변수는 메모리에서 추후 제거됨).
예: titanic_df = titanic_df.drop(' Age_0', axis=1, inplace=False )

## - 5) Index 객체

- 판다스의 Index 객체는 RDBMS의 PK(Primary Key)와 유사하게 DataFrame, Series의 레코드를 고유하게 식별하는 객체

In [177]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('titanic_train.csv')

# Index 객체 추출
indexes = titanic_df.index
print(indexes)

# Index 객체를 실제 값 arrray로 변환
print('Index 객체 array값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [125]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

- 한 번 만들어진 DataFrame 및 Series의 Index 객체는 함부로 변경할 수 없음

In [126]:
indexes[0] = 5

TypeError: Index does not support mutable operations

In [129]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:',sum(series_fair))
print('Fair Series + 3:\n', (series_fair + 3).head(3) )

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.9493
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

- DataFrame 및 Series에 reset_index() 메서드를 수행하면 새롭게 인덱스를 연속 숫자 형으로 할당
하며 기존 인덱스는 'index'라는 새로운 칼럼 명으로 추가

In [131]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

- reset_index()는 인덱스가 연속된 int 숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들 때 주로 사용
- Series에 reset_index()를 적용하면 Series가 아닌 DataFrame이 반환

In [132]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.DataFrame'>

- reset_index( )의 parameter 중 drop=True로 설정하면 기존 인덱스는 새로운 칼럼으로 추가되지 않고 삭제(drop)되며, 새로운 칼럼이 추가되지 않으므로 그대로 Series로 유지함

## - 6) 데이터 셀렉션 및 필터링

- 넘파이의 경우 '[ ]' 연산자 내 단일 값 추출, 슬라이싱, 팬시 인덱싱, 불린 인덱싱을 통해 데이터를 추출
- 판다스의 경우 iloc[], loc[] 연산자를 통해 동일한 작업을 수행

(1) DataFrame의 [ ] 연산자

DataFrame 바로 뒤에 있는 '[ ]' 안에 들어갈 수 있는 것은 칼럼명 문자(또는 칼럼명의 리스트 객체), 또는 인덱스로 변환 가능한 표현식 (칼럼 지정 연산자)

In [133]:
print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3))
print('[ ] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

판다스의 인덱스 형태로 변환 가능한 표현식은 [] 내에 입력 가능 & 불린 인덱싱도 가능

In [135]:
titanic_df[0:2]

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [138]:
titanic_df[ titanic_df['Pclass'] == 3].head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

<DataFrame 뒤의 [ ] 연산자의 입력 인자>

- DataFrame 바로 뒤의 [ ] 연산자는 넘파이의 [ ]나 Series의 [ ]와 다름
- DataFrame 바로 뒤의 [ ] 내 입력값은 칼럼명(또는 칼럼의 리스트)을 지정해 칼럼 지정 연산에 사용하거나 불린 인덱스
용도로만 사용해야함.
- DataFrame [0:2]와 같은 슬라이싱 연산으로 데이터를 추출하는 방법은 사용하지 않는 게 좋음

(2) DataFrame iloc[ ] 연산자

iloc[ ], loc[ ]: 로우나 칼럼을 지정하여 데이터를 선택할 수 있는 인덱싱 방식
- iloc[ ]: 위치(Location) 기반 인덱싱 방식으로 동작 (행과 열 위치를, 0을 출발점으로 하는 세로축, 가로축 좌표 정숫값으로 지정하는 방식)
- loc[ ]: 명칭(Label)기반 인덱싱 방식으로 동작 (데이터 프레임의 인덱스 값으로 행 위치를, 칼럼의 명칭으로 열 위치를 지정하는 방식)

iloc[ ]는 위치 기반 인덱싱만 허용하기 때문에 행과 열의 좌표 위치에 해당하는 값으로 정숫값 또는 정수형의 슬라이싱, 팬시 리스트 값 입력

In [140]:
data = {'Name': ['Chulmin', 'Eunkyung1','Jinwoong', 'Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male1', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

            Name  Year  Gender
one      Chulmin  2011   Male1
two    Eunkyung1  2016  Female
three   Jinwoong  2015    Male
four     Soobeom  2015    Male

In [141]:
data_df.iloc[0,0]

'Chulmin'

In [142]:
# 아래 코드는 오류를 발생시킵니다. (칼럼명 입력 시 오류 발생)
data_df.iloc[0, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [143]:
# 아래 코드는 오류를 발생합니다. (인덱스 값 'one' 입)
data_df.iloc['one', 0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

iloc[ ]는 열 위치에 -1을 입력하여 DataFrame의 가장 마지막 열 데이터를 가져오는데, 이는 넘파이와 같음

In [144]:
print("\n 맨 마지막 칼럼 데이터 [:, -1 ] \n", data_df.iloc[:, -1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:,:-1] \n", data_df.iloc[: , :-1])

 맨 마지막 칼럼 데이터 [:, -1 ]
 one       Male1
two      Female
three      Male
four       Male
Name: Gender, dtype: str

 맨 마지막 칼럼을 제외한 모든 데이터 [:,:-1]
             Name  Year
one      Chulmin  2011
two    Eunkyung1  2016
three   Jinwoong  2015
four     Soobeom  2015

(3) DataFrame loc[] 연산자

- 행 위치에는 DataFrame 인덱스 값을, 그리고 열 위치에는 칼럼명을 입력해서 loc[인덱스값, 칼럼명]와 같은 형식으로 데이터를 추출

In [147]:
data_df.loc['one', 'Name']

'Chulmin'

In [148]:
# 다음 코드는 오류를 발생시킵니다. (행 위치에 0 입력)
data_df.loc[0, 'Name']

KeyError: 0

loc[ ]에 슬라이싱 기호를 적용하면 종료 값-1이 아니라 종료 값까지 포함을 의미 -> 이유: 명칭 기반 인덱싱의 특성(명칭은 숫자형이 아닐 수도 있기에)

In [151]:
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0],'\n')
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name' ])

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: str

명칭기반 loc slicing
 one      Chulmin
two    Eunkyung1
Name: Name, dtype: str

< [ ], iloc[ ], loc[ ]의 특징과 주의사항>

1. 개별 또는 여러 칼럼 값 전체를 추출하고자 한다면 iloc[ ]나 loc[ ]를 사용하지 않고 data_df['Name']과 같이
DataFrame['칼럼명']만으로 충분함. 하지만 행과 열을 함께 사용하여 데이터를 추출해야 한다면 iloc[ ]나
loc[]를 사용해야 함.
2. iloc[ ]와 loc[ ｝를 이해하기 위해서는 명칭 기반 인덱싱과 위치 기반 인덱싱의 차이를 먼저 이해해야 함
DataFrame의 인덱스나 칼럼명으로 데이터에 접근하는 것은 명칭 기반 인덱싱임. 0부터 시작하는 행, 열의 위
치 좌표에만 의존하는 것이 위치 기반 인덱싱임.
3. iloc[]는 위치 기반 인덱싱만 가능함. 따라서 행과 열 위치 값으로 정수형 값을 지정해 원하는 데이터를 반환함.
4. Ioc[ ]는 명칭 기반 인덱싱만 가능함. 따라서 행 위치에 DataFrame 인덱스가 오며, 열 위치에는 칼럼명을 지정
해 원하는 데이터를 반환함.
5. 명칭 기반 인덱싱에서 슬라이싱을 '시작점:종료점'으로 지정할 때 시작점에서 종료점을 포함한 위치에 있는 데이터
를 반환함

(4) 불린 인덱싱

불린 인덱싱은 [ ], loc[ ]에서 공통으로 지원하나, iloc[ ]는 정수형 값이 아닌 불린 값에 대해서는 지원하지 않기 때문에 불린 인덱싱이 지원되지 않음

In [154]:
titanic_df = pd.read_csv('titanic_train.csv')
titanic_boolean = titanic_df[titanic_df['Age']> 60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [155]:
titanic_df[titanic_df['Age'] > 60][['Name', 'Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [156]:
titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [157]:
titanic_df[ (titanic_df['Age'] > 60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [161]:
condl = titanic_df['Age'] > 60
cond2 = titanic_df ['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[condl & cond2 & cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       1  Wheadon, Mr...  female  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...  female  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...  female  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       1  Connors, Mr...  female  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...  female  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...  female  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       1  Duane, Mr. ...  female  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       1  Nysveen, Mr...  female  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...  female  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....  female  65.0      0      0        13509   26.5500          E38        S
483          484         1       1  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...  female  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...  female  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....  female  62.0      0      0       113807   26.5500          NaN        S
570          571         1       1  Harris, Mr....  female  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....  female  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...  female  80.0      0      0        27042   30.0000          A23        S
672          673         0       1  Mitchell, M...  female  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...  female  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       1  Svensson, M...  female  74.0      0      0       347060    7.7750          NaN        S

## - 7) 정렬, Aggregation 함수, GroupBy 적용
(1) DataFrame, Series의 정렬 - sort_values()

sort_values( )의 주요 입력 파라미터
- by로 특정 칼럼을 입력하면 해당 칼럼으로 정렬을 수행
- ascending= True로 설정하면 오름차순으로 정렬
- inplace=False로 설정하면 sort_values( )를 호출한 DataFrame은 그대로 유지하며 정렬된 DataFrame을 결과로 반환 & inplace=True로 설정하면 호출한 DataFrame의 정렬 결과를 그대로 적용 (기본: inplace=False)

In [162]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       1  Abbing, Mr....  female  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       1  Abbott, Mr....  female  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       1  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [176]:
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False) # 내림차순
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked
868          869         0       1  van Melkebe...  female   NaN      0      0         345777   9.5000   NaN        S
153          154         0       1  van Billiar...  female  40.5      0      2       A/5. 851  14.5000   NaN        S
361          362         0       1  del Carlo, ...  female  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C

(2) Aggregation 함수 적용

- aggregation 함수: min( ), max( ), sum( ), count( )
- DataFrame에서 바로 aggregation을 호출할 경우 모든 칼럼에 해당 aggregation을 적용

In [172]:
titanic_df.count()   # count: 데이터프레임이나 시리즈(Series) 내에서 결측치(NaN, Null)를 제외한 '유효한 데이터의 개수'를 세어주는 함수

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [173]:
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

(3) groupby() 적용
- DataFrame의 groupby() 사용 시 입력 파라미터 by에 칼럼을 입력하면 대상 칼럼으로 groupby
- DataFrame에 groupby()를 호출하면 DataFrameGroupBy라는 또 다른 형태의 DataFrame을 반환

In [174]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.api.typing.DataFrameGroupBy'>

- DataFrame에 groupby()를 호출해 반환된 결과에 aggregation 함수를 호출하면 groupby() 대상 칼럼을 제외한 모든 칼럼에 해당 aggregation 함수를 적용 (SQL과의 차이)

In [181]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

- DataFrame의 groupby( )에 특정 칼럼만 aggregation 함수를 적용하려면 grouby( )로 반환된 DataFrameGroupBy 객체에 해당 칼럼을 필터링한 뒤 aggregation 함수를 적용
- SQL의 경우 group by 적용 시 여러 개의 칼럼에 aggregation 함수를 호출하려면 대상 칼럼을 모두 Select 절에 나열

In [184]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

- DataFrame groupby()의 경우 적용하려는 여러 개의 aggregation 함수명을 DataFrameGroupBy 객체의 agg( ) 내에 인자로 입력해서 사용
- SQL의 경우 서로 다른 aggregation 함수를 적용할 경우에는 Select 절에 나열

In [185]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

여러 개의 칼럼이 서로 다른 aggregation 함수를 groupby에서 호출
- SQL: Select max(Age), sum(SibSp), avg(Fare) from titanic_tablegroup by Pclass와 같이 쉽게 가능
- DataFrame: agg()를 이용해 이 같은 처리가 가능한데, agg() 내에 입력값으로 딕셔너리 형태로 aggregation이 적용될 칼럼들과 aggregation 함수를 입력

In [186]:
agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

## - 8) 결손 데이터 처리하기

결손 데이터: 칼럼에 값이 없는, 즉 NULL인 경우 (넘파이-NaN)
- 머신러닝 알고리즘은 이 NaN 값을 처리하지 않으므로 이 값을 다른 값으로 대체해야 함

(1) isna()로 결손 데이터 여부 확인

In [187]:
titanic_df.isna().head(3)

   PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [189]:
titanic_df.isna( ).sum( )  # 결손 데이터 개수

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

(2) fillna()로 결손 데이터 대체하기

In [190]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

fillna()를 이용해 반환 값을 다시 받거나 inplace=True 파라미터를 fillna()에 추가해야 실제 데이터 세트 값이 변경됨
- -> 1) titanic_df['Cabin'] = titanic_df['Cabin'].fillna(COOO')와 같이 fillna() 반환 값을 다시 titanic_df['Cabin'] 정해주기
- -> 2) titanic_df['Cabin'].fillna('COOO', inplace=True)와 같이 inplace=True를 설정하기 (반환값 지정 X 경우)

In [192]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'] .mean()) # 'Age' 칼럼의 NaN 값을 평균 나이로, 'Embarked' 칼럼의 NaN 값을 'S'로 대체
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## - 9) apply lambda 식으로 데이터 가공

: apply 함수에 lambda 식을 결합해 DataFrame이나 Series의 레코드별로 데이터를 가공하는 기능

In [194]:
def get_square(a):
    return a**2

print('3의 제곱은:', get_square(3))

3의 제곱은: 9

In [197]:
lambda_square = lambda x : x ** 2
print('3의 제곱은:', lambda_square(3))

3의 제곱은: 9

lambda x:x ** 2에서 ':'로 입력 인자와 반환될 입력 인자의 계산식을 분리
- ':'의 왼쪽에 있는 x는 입력 인자를 가리키며, 오른쪽은 입력 인자의 계산식(=> 반환값)

In [199]:
a=[1, 2, 3]
squares = map(lambda x : x**2, a)  #여러 개의 값을 입력 인자로 사용해야 할 경우 -> map() 이용
list(squares)

[1, 4, 9]

In [204]:
titanic_df['Name_len']= titanic_df['Name'].apply(lambda x:len(x)) # 'Name' 칼럼의 문자열 개수를 별도의 칼럼인 'Name_len'에 생성
titanic_df[['Name', 'Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [206]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult' ) # 나이가 15세 미만이면 'Child', 그렇지 않으면 'Adult'로 구분하는 새로운 칼럼 ‘Child_Adulf
titanic_df[['Age', 'Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

if else만 지원하며, if 절의 경우 if 식보다 반환 값을 먼저 기술해야 함 (lambda 식 ':' 기호의 오른편에 반환 값이 있어야 하기 때문)

In [207]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60
else 'Elderly')) #나이가 15세 이하면 Child, 15〜60세 사이는 Adult, 61세 이상은 Elderly로 분류하는 'Age_Cat' 칼럼
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [211]:
# 5살 이하는 Baby, 12살 이하는 Child, 18살 이하는 Teenage, 25살 이하는 Student, 35살 이하는 Young Adult, 60세 이하는 Adult, 그리고 그 이상은 Elderly로 분류
# 나이에 따라 세분화된 분류를 수행하는 함수 생성.
def get_category(age):
    cat = ''
    if age <= 5:cat = 'Baby'
    elif age <= 12:cat = 'Child'
    elif age <= 18:cat = 'Teenager'
    elif age <= 25:cat = 'Student'
    elif age <= 35:cat = 'Young Adult'
    elif age <= 60:cat = 'Adult'
    else : cat = 'Elderly'
        
    return cat
# lambda 식에 위에서 생성한 get_category( ) 함수를 반환값으로 지정.
# get_category(X)는 입력값으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age', 'Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult